"""Schema-driven overlay/config field descriptors for the config page and PUT API."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from irswitch.overlay.settings import OverlaySettings

FieldType = Literal["float", "int", "bool", "str"]


@dataclass(frozen=True)
class FieldSpec:
    key: str
    field_type: FieldType
    default: Any
    live: bool
    section: str
    help: str
    minimum: float | None = None
    maximum: float | None = None
    optional: bool = False
    choices: tuple[str, ...] | None = None
    secret: bool = False


OVERLAY_FIELDS: tuple[FieldSpec, ...] = (
    FieldSpec(
        "overlay.enabled",
        "bool",
        True,
        True,
        "overlay",
        "Enable race overlay pipeline.",
    ),
    FieldSpec(
        "overlay.theme",
        "str",
        "cyber_racing",
        True,
        "overlay",
        "Theme id (same widget geometry, different tokens).",
        choices=(
            "cyber_racing",
            "stealth_graphite",
            "night_attack",
            "pit_wall_dark",
            "pit_wall_light",
        ),
    ),
    FieldSpec("overlay.debug", "bool", False, True, "overlay", "Verbose overlay debug logging."),
    FieldSpec(
        "overlay.language",
        "str",
        "en",
        True,
        "overlay",
        "Overlay copy language. English is the base catalog; missing "
        "translations fall back to it.",
        choices=("en", "cs"),
    ),
    FieldSpec(
        "overlay.v4_assets",
        "bool",
        False,
        True,
        "overlay",
        "Serve overlay V4 asset pack (preview; default off).",
    ),
    FieldSpec(
        "overlay.v4_renderer",
        "bool",
        False,
        True,
        "overlay",
        "Use overlay V4 renderer instead of the current one (preview; default off).",
    ),
    FieldSpec(
        "overlay.session_tape",
        "bool",
        True,
        True,
        "overlay",
        "Write a session JSONL tape of overlay events, decisions, and widgets.",
    ),
    FieldSpec(
        "overlay.session_tape_dir",
        "str",
        "recordings",
        False,
        "overlay",
        "Directory for overlay session JSONL files (restart to change).",
    ),
    FieldSpec(
        "event_engine.v2_payload",
        "bool",
        False,
        True,
        "event_engine",
        "Emit V2 event envelopes with copy tokens (preview; default off).",
    ),
    FieldSpec(
        "event_engine.practice",
        "bool",
        False,
        True,
        "event_engine",
        "Enable practice-session event detectors (preview; default off).",
    ),
    FieldSpec(
        "event_engine.quali_projection",
        "bool",
        False,
        True,
        "event_engine",
        "Enable qualifying lap-time projection events (preview; default off).",
    ),
    FieldSpec(
        "event_engine.overtake_classifier",
        "bool",
        False,
        True,
        "event_engine",
        "Classify overtakes (on-track, pit-cycle, retirement) (preview; default off).",
    ),
    FieldSpec(
        "event_engine.pit_story",
        "bool",
        False,
        True,
        "event_engine",
        "Enable multi-stage pit-stop narrative events (preview; default off).",
    ),
    FieldSpec(
        "event_engine.hr_pressure",
        "bool",
        False,
        True,
        "event_engine",
        "Derive driver-pressure events from heart rate (preview; default off).",
    ),
    FieldSpec(
        "commentary.enabled",
        "bool",
        False,
        True,
        "commentary",
        "Speak accepted Event Engine stories via the commentary graph (preview; default off).",
    ),
    FieldSpec(
        "commentary.use_hr_emotion",
        "bool",
        True,
        True,
        "commentary",
        "Use BLE HR state to pick emotion variants. Missing HR falls back to unknown/neutral.",
    ),
    FieldSpec(
        "commentary.cooldown_s",
        "float",
        4.0,
        True,
        "commentary",
        "Minimum seconds between any spoken lines (voice anti-spam, separate from overlay).",
        0.5,
        30.0,
    ),
    FieldSpec(
        "commentary.max_utterance_s",
        "float",
        6.0,
        True,
        "commentary",
        "Hard cap for estimated spoken duration.",
        1.0,
        12.0,
    ),
    FieldSpec(
        "commentary.tts_backend",
        "str",
        "auto",
        True,
        "commentary",
        "TTS engine: auto (SAPI on Windows, espeak-ng on Linux), sapi, espeak, or null.",
        choices=("auto", "sapi", "espeak", "null"),
    ),
    FieldSpec(
        "commentary.tts_voice",
        "str",
        "",
        True,
        "commentary",
        "Optional installed voice name. Empty = system default.",
        optional=True,
    ),
    FieldSpec(
        "commentary.tts_rate",
        "int",
        0,
        True,
        "commentary",
        "SAPI-style rate (-10 slow … 10 fast). Browser preview maps this to SpeechSynthesis.rate.",
        -10.0,
        10.0,
    ),
    FieldSpec(
        "commentary.audio_device",
        "str",
        "",
        True,
        "commentary",
        "Windows playback device substring for SAPI (e.g. CABLE Input). Empty = default output. 16ch endpoints are skipped when a stereo match exists.",
        optional=True,
    ),
    FieldSpec(
        "commentary.duck_input",
        "str",
        "",
        True,
        "commentary",
        "OBS audio input to duck while commentary speaks (e.g. Zvuk plochy). Empty = no ducking.",
        optional=True,
    ),
    FieldSpec(
        "commentary.duck_ratio",
        "float",
        0.25,
        True,
        "commentary",
        "Fraction of the original OBS volume while commentary speaks (0.25 = 25%).",
        0.0,
        1.0,
    ),
    FieldSpec(
        "commentary.duck_fade_ms",
        "int",
        750,
        True,
        "commentary",
        "Fade-out and fade-in duration in milliseconds when ducking OBS audio (0 = instant).",
        0.0,
        3000.0,
    ),
    FieldSpec(
        "commentary.decision_log_size",
        "int",
        32,
        True,
        "commentary",
        "How many recent speak/skip decisions to keep for /api/commentary/decisions.",
        1.0,
        200.0,
    ),
    FieldSpec(
        "commentary.sector_speak",
        "bool",
        False,
        True,
        "commentary",
        "Speak notable sector splits / sector bests (HUD SECTOR_SPLIT stays on its own flags; default off).",
    ),
    FieldSpec(
        "commentary.sector_speak_max_per_lap",
        "int",
        1,
        True,
        "commentary",
        "Max sector commentary lines per lap when sector_speak is on (0 = mute sector speak).",
        0.0,
        8.0,
    ),
    FieldSpec(
        "commentary.session_briefs",
        "bool",
        False,
        True,
        "commentary",
        "Speak once-per-session intro / SoF / weather briefs (commentary sidecars; default off).",
    ),
    FieldSpec(
        "commentary.stream_start",
        "bool",
        False,
        True,
        "commentary",
        "Speak a welcome line when OBS streaming starts (commentary-only; default off).",
    ),
    FieldSpec(
        "commentary.gap_hunt_tts_in_practice",
        "bool",
        False,
        True,
        "commentary",
        "Speak gap-hunt (HUNTING/HUNTED) TTS in practice. HUD hunting is independent. Default off.",
    ),
    FieldSpec(
        "commentary.gap_hunt_tts_in_qualifying",
        "bool",
        False,
        True,
        "commentary",
        "Speak gap-hunt (HUNTING/HUNTED) TTS in qualifying. HUD hunting is independent. Default off.",
    ),
    FieldSpec(
        "race_observer.leader_pace_cooldown_s",
        "float",
        300.0,
        True,
        "race_observer",
        "Minimum seconds between leader field-fact fillers. Other filler kinds still rotate.",
        minimum=0.0,
        maximum=3600.0,
    ),
    FieldSpec(
        "race_observer.incident_classify",
        "bool",
        False,
        True,
        "race_observer",
        "Set INCIDENT metrics.branch to off_track or unknown. Nearby cars stay metrics only. Default off.",
    ),
    FieldSpec(
        "race_observer.flags",
        "bool",
        False,
        True,
        "race_observer",
        "Speak race yellow/green/checkered as SESSION_FLAG. Start lights ignored. Default off.",
    ),
    FieldSpec(
        "commentary.llm_polish",
        "bool",
        False,
        True,
        "commentary",
        "Polish authored skeleton lines via OpenAI-compatible HTTP (e.g. Ollama). Default off.",
    ),
    FieldSpec(
        "commentary.llm_base_url",
        "str",
        "http://127.0.0.1:11434/v1",
        True,
        "commentary",
        "OpenAI-compatible base URL for commentary LLM polish.",
    ),
    FieldSpec(
        "commentary.llm_model",
        "str",
        "qwen2.5:3b",
        True,
        "commentary",
        "Model id for commentary LLM polish.",
    ),
    FieldSpec(
        "commentary.llm_timeout_s",
        "float",
        8.0,
        True,
        "commentary",
        "HTTP wall-clock budget for the whole polish including retries (seconds). "
        "On failure skip TTS; do not speak the skeleton.",
        0.5,
        120.0,
    ),
    FieldSpec(
        "commentary.llm_temperature",
        "float",
        0.45,
        True,
        "commentary",
        "LLM temperature for polish requests.",
        0.0,
        2.0,
    ),
    FieldSpec(
        "commentary.llm_max_tokens",
        "int",
        220,
        True,
        "commentary",
        "Ceiling for polish completion tokens. The request may send fewer, capped to the node TTS budget.",
        32.0,
        800.0,
    ),
    FieldSpec(
        "commentary.llm_max_attempts",
        "int",
        5,
        True,
        "commentary",
        "Max HTTP polish attempts per line (1–8). Failed polish is silent, not skeleton.",
        1.0,
        8.0,
    ),
    FieldSpec(
        "commentary.driver_name",
        "str",
        "",
        True,
        "commentary",
        "Spoken given name for the featured driver. Empty = iRacing UserName first token.",
        optional=True,
    ),
    FieldSpec(
        "commentary.driver_nickname",
        "str",
        "",
        True,
        "commentary",
        "Spoken nickname mixed with driver_name. Empty = iRacing UserName last token.",
        optional=True,
    ),
    FieldSpec(
        "sampling.default_hz",
        "float",
        5.0,
        True,
        "sampling",
        "Global sample rate. Components may override.",
        0.2,
        30.0,
    ),
    FieldSpec(
        "sampling.race.hz",
        "float",
        None,
        True,
        "sampling.race",
        "Race telemetry Hz. Empty = global default.",
        0.2,
        30.0,
        optional=True,
    ),
    FieldSpec(
        "sampling.system.hz",
        "float",
        None,
        True,
        "sampling.system",
        "System info Hz. Empty = global default.",
        0.2,
        30.0,
        optional=True,
    ),
    FieldSpec(
        "sampling.bio.hz",
        "float",
        None,
        True,
        "sampling.bio",
        "Heart-rate poll Hz. Empty or 0 = BLE notifications (push).",
        0.0,
        30.0,
        optional=True,
    ),
    FieldSpec(
        "battle.hunting.enter_gap",
        "float",
        3.0,
        True,
        "battle.hunting",
        "Enter hunting when gap < this (s).",
        0.1,
        20.0,
    ),
    FieldSpec(
        "battle.hunting.exit_gap",
        "float",
        4.0,
        True,
        "battle.hunting",
        "Exit hunting when gap > this (s).",
        0.1,
        30.0,
    ),
    FieldSpec(
        "battle.hunting.min_closing_rate",
        "float",
        0.10,
        True,
        "battle.hunting",
        "Minimum closing rate (s/s).",
        0.0,
        5.0,
    ),
    FieldSpec(
        "battle.hunting.activation_delay",
        "float",
        2.0,
        True,
        "battle.hunting",
        "Seconds conditions must hold before ENTER.",
        0.0,
        15.0,
    ),
    FieldSpec(
        "battle.hunting.exit_delay",
        "float",
        1.5,
        True,
        "battle.hunting",
        "Seconds conditions must fail before EXIT.",
        0.0,
        15.0,
    ),
    FieldSpec(
        "battle.hunting.approach_enter_gap",
        "float",
        1.5,
        True,
        "battle.hunting",
        "Escalate hunting to approach when gap <= this (s).",
        0.05,
        10.0,
    ),
    FieldSpec(
        "battle.hunting.approach_exit_gap",
        "float",
        1.8,
        True,
        "battle.hunting",
        "De-escalate approach when gap > this (s).",
        0.05,
        10.0,
    ),
    FieldSpec(
        "battle.hunting.attack_enter_gap",
        "float",
        0.8,
        True,
        "battle.hunting",
        "Escalate approach to attack range when gap <= this (s).",
        0.05,
        5.0,
    ),
    FieldSpec(
        "battle.hunting.attack_exit_gap",
        "float",
        1.0,
        True,
        "battle.hunting",
        "De-escalate attack range when gap > this (s).",
        0.05,
        5.0,
    ),
    FieldSpec(
        "battle.hunting.side_by_side_enter_gap",
        "float",
        0.35,
        True,
        "battle.hunting",
        "Escalate attack range to side-by-side when gap <= this (s).",
        0.05,
        2.0,
    ),
    FieldSpec(
        "battle.hunting.side_by_side_exit_gap",
        "float",
        0.45,
        True,
        "battle.hunting",
        "De-escalate side-by-side when gap > this (s).",
        0.05,
        2.0,
    ),
    FieldSpec(
        "battle.hunting.intensity_min_closing_rate",
        "float",
        0.15,
        True,
        "battle.hunting",
        "Minimum closing rate (s/s) for battle intensity escalation.",
        0.0,
        5.0,
    ),
    FieldSpec(
        "battle.hunting.min_intensity_hold_s",
        "float",
        2.5,
        True,
        "battle.hunting",
        "Minimum seconds between hunting intensity ladder swaps.",
        0.0,
        15.0,
    ),
    FieldSpec(
        "battle.hunting.update_min_interval_s",
        "float",
        1.0,
        True,
        "battle.hunting",
        "Minimum seconds between battle UPDATE envelopes (gap-unchanged).",
        0.25,
        10.0,
    ),
    FieldSpec(
        "battle.hunting.update_gap_epsilon_s",
        "float",
        0.08,
        True,
        "battle.hunting",
        "Gap change (s) that forces an early battle UPDATE.",
        0.0,
        2.0,
    ),
    FieldSpec(
        "battle.overtake.max_gap",
        "float",
        2.5,
        True,
        "battle.overtake",
        "Max gap (s) to classify a position gain as an on-track overtake.",
        0.1,
        10.0,
    ),
    FieldSpec(
        "battle.overtake.min_closing_rate",
        "float",
        0.08,
        True,
        "battle.overtake",
        "Minimum closing rate (s/s) required for overtake classification.",
        0.0,
        5.0,
    ),
    FieldSpec(
        "battle.hunted.enter_gap",
        "float",
        3.0,
        True,
        "battle.hunted",
        "Enter hunted when gap < this (s).",
        0.1,
        20.0,
    ),
    FieldSpec(
        "battle.hunted.exit_gap",
        "float",
        4.0,
        True,
        "battle.hunted",
        "Exit hunted when gap > this (s).",
        0.1,
        30.0,
    ),
    FieldSpec(
        "battle.hunted.min_closing_rate",
        "float",
        0.10,
        True,
        "battle.hunted",
        "Minimum closing rate (s/s).",
        0.0,
        5.0,
    ),
    FieldSpec(
        "battle.hunted.activation_delay",
        "float",
        2.0,
        True,
        "battle.hunted",
        "Seconds conditions must hold before ENTER.",
        0.0,
        15.0,
    ),
    FieldSpec(
        "battle.hunted.exit_delay",
        "float",
        1.5,
        True,
        "battle.hunted",
        "Seconds conditions must fail before EXIT.",
        0.0,
        15.0,
    ),
    FieldSpec(
        "battle.position_stable_seconds",
        "float",
        1.0,
        True,
        "battle",
        "Position must be stable this long before emit.",
        0.3,
        5.0,
    ),
    FieldSpec(
        "battle.gap_history_seconds",
        "float",
        3.0,
        True,
        "battle",
        "Rolling window for closing-rate regression.",
        1.0,
        8.0,
    ),
    FieldSpec(
        "heart_rate.enabled", "bool", True, True, "heart_rate", "Enable BLE heart-rate provider."
    ),
    FieldSpec(
        "heart_rate.source", "str", "bluetooth", True, "heart_rate", "HR source (bluetooth)."
    ),
    FieldSpec(
        "heart_rate.bluetooth.device",
        "str",
        "auto",
        True,
        "heart_rate.bluetooth",
        "Device name/address, or auto (advertised Heart Rate UUID 0x180D).",
    ),
    FieldSpec(
        "heart_rate.bluetooth.reconnect",
        "bool",
        True,
        True,
        "heart_rate.bluetooth",
        "Auto-reconnect on disconnect.",
    ),
    FieldSpec(
        "heart_rate.baseline_window",
        "float",
        300.0,
        True,
        "heart_rate",
        "Rolling baseline window in seconds.",
        30.0,
        1800.0,
    ),
    FieldSpec(
        "heart_rate.calm_delta",
        "float",
        5.0,
        True,
        "heart_rate",
        "Delta BPM below this is CALM.",
        0.0,
        50.0,
    ),
    FieldSpec(
        "heart_rate.focused_delta",
        "float",
        15.0,
        True,
        "heart_rate",
        "Delta BPM below this is FOCUSED.",
        0.0,
        80.0,
    ),
    FieldSpec(
        "heart_rate.pushing_delta",
        "float",
        25.0,
        True,
        "heart_rate",
        "Delta BPM below this is PUSHING; above is HIGH.",
        0.0,
        100.0,
    ),
    FieldSpec(
        "system_info.enabled", "bool", True, True, "system_info", "Enable system info provider."
    ),
    FieldSpec(
        "system_info.cpu.enabled", "bool", True, True, "system_info.cpu", "Read CPU sensors."
    ),
    FieldSpec(
        "system_info.gpu.enabled",
        "bool",
        True,
        True,
        "system_info.gpu",
        "Read NVIDIA GPU via NVML.",
    ),
    FieldSpec(
        "system_info.memory.enabled",
        "bool",
        True,
        True,
        "system_info.memory",
        "Read RAM via psutil.",
    ),
    FieldSpec(
        "system_info.lhm_dll_path",
        "str",
        None,
        False,
        "system_info",
        "Optional LibreHardwareMonitorLib.dll path. Empty = unused; "
        "CPU package sensors come from LHM HTTP /data.json (0.9.5+) or older WMI.",
        optional=True,
    ),
    FieldSpec(
        "system_info.cpu_temp_warn",
        "float",
        80.0,
        True,
        "system_info",
        "CPU warning temperature °C.",
        40.0,
        120.0,
    ),
    FieldSpec(
        "system_info.cpu_temp_crit",
        "float",
        95.0,
        True,
        "system_info",
        "CPU critical temperature °C.",
        50.0,
        130.0,
    ),
    FieldSpec(
        "system_info.gpu_temp_warn",
        "float",
        80.0,
        True,
        "system_info",
        "GPU warning temperature °C.",
        40.0,
        120.0,
    ),
    FieldSpec(
        "system_info.gpu_temp_crit",
        "float",
        90.0,
        True,
        "system_info",
        "GPU critical temperature °C.",
        50.0,
        130.0,
    ),
    FieldSpec(
        "events.system_events_on_overlay",
        "bool",
        False,
        True,
        "events",
        "Show CPU/GPU alerts on the stream overlay (default: debug only).",
    ),
    FieldSpec(
        "events.incident_min_delta",
        "int",
        2,
        True,
        "events",
        "Minimum incident delta to show.",
        1,
        16,
    ),
    FieldSpec(
        "events.lap_duration",
        "float",
        4.0,
        True,
        "events",
        "Lap widget display seconds.",
        1.0,
        15.0,
    ),
    FieldSpec(
        "events.lap_cooldown",
        "float",
        5.0,
        True,
        "events",
        "Lap event cooldown seconds.",
        0.0,
        30.0,
    ),
    FieldSpec(
        "events.priorities.hunting",
        "int",
        20,
        True,
        "events.priorities",
        "Hunting priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.hunted", "int", 20, True, "events.priorities", "Hunted priority.", 1, 100
    ),
    FieldSpec(
        "events.priorities.lap_complete",
        "int",
        40,
        True,
        "events.priorities",
        "Lap complete priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.personal_best",
        "int",
        60,
        True,
        "events.priorities",
        "Personal best priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.position_change",
        "int",
        70,
        True,
        "events.priorities",
        "Position change priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.incident",
        "int",
        90,
        True,
        "events.priorities",
        "Incident priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.final_lap",
        "int",
        95,
        True,
        "events.priorities",
        "Final lap priority.",
        1,
        100,
    ),
    FieldSpec(
        "events.priorities.finish",
        "int",
        100,
        True,
        "events.priorities",
        "Finish priority.",
        1,
        100,
    ),
)

_FIELD_BY_KEY = {spec.key: spec for spec in OVERLAY_FIELDS}


def field_by_key(key: str) -> FieldSpec | None:
    return _FIELD_BY_KEY.get(key)


def schema_as_dicts() -> list[dict[str, Any]]:
    rows = []
    for spec in OVERLAY_FIELDS:
        rows.append(
            {
                "key": spec.key,
                "type": spec.field_type,
                "default": spec.default,
                "live": spec.live,
                "section": spec.section,
                "help": spec.help,
                "min": spec.minimum,
                "max": spec.maximum,
                "optional": spec.optional,
                "choices": list(spec.choices) if spec.choices else None,
                "secret": spec.secret,
            }
        )
    return rows


def overlay_values(settings: OverlaySettings) -> dict[str, Any]:
    """Flatten OverlaySettings to dotted keys used by the config UI."""
    s = settings
    return {
        "overlay.enabled": s.enabled,
        "overlay.theme": s.theme,
        "overlay.debug": s.debug,
        "overlay.language": s.language,
        "overlay.v4_assets": s.v4.assets,
        "overlay.v4_renderer": s.v4.renderer,
        "overlay.session_tape": s.tape.enabled,
        "overlay.session_tape_dir": s.tape.directory,
        "event_engine.v2_payload": s.event_engine.v2_payload,
        "event_engine.practice": s.event_engine.practice,
        "event_engine.quali_projection": s.event_engine.quali_projection,
        "event_engine.overtake_classifier": s.event_engine.overtake_classifier,
        "event_engine.pit_story": s.event_engine.pit_story,
        "event_engine.hr_pressure": s.event_engine.hr_pressure,
        "commentary.enabled": s.commentary.enabled,
        "commentary.use_hr_emotion": s.commentary.use_hr_emotion,
        "commentary.cooldown_s": s.commentary.cooldown_s,
        "commentary.max_utterance_s": s.commentary.max_utterance_s,
        "commentary.tts_backend": s.commentary.tts_backend,
        "commentary.tts_voice": s.commentary.tts_voice,
        "commentary.tts_rate": s.commentary.tts_rate,
        "commentary.audio_device": s.commentary.audio_device,
        "commentary.duck_input": s.commentary.duck_input,
        "commentary.duck_ratio": s.commentary.duck_ratio,
        "commentary.duck_fade_ms": s.commentary.duck_fade_ms,
        "commentary.decision_log_size": s.commentary.decision_log_size,
        "commentary.sector_speak": s.commentary.sector_speak,
        "commentary.sector_speak_max_per_lap": s.commentary.sector_speak_max_per_lap,
        "commentary.session_briefs": s.commentary.session_briefs,
        "commentary.stream_start": s.commentary.stream_start,
        "commentary.gap_hunt_tts_in_practice": s.commentary.gap_hunt_tts_in_practice,
        "commentary.gap_hunt_tts_in_qualifying": s.commentary.gap_hunt_tts_in_qualifying,
        "race_observer.leader_pace_cooldown_s": s.race_observer.leader_pace_cooldown_s,
        "race_observer.incident_classify": s.race_observer.incident_classify,
        "race_observer.flags": s.race_observer.flags,
        "commentary.llm_polish": s.commentary.llm_polish,
        "commentary.llm_base_url": s.commentary.llm_base_url,
        "commentary.llm_model": s.commentary.llm_model,
        "commentary.llm_timeout_s": s.commentary.llm_timeout_s,
        "commentary.llm_temperature": s.commentary.llm_temperature,
        "commentary.llm_max_tokens": s.commentary.llm_max_tokens,
        "commentary.llm_max_attempts": s.commentary.llm_max_attempts,
        "commentary.driver_name": s.commentary.driver_name,
        "commentary.driver_nickname": s.commentary.driver_nickname,
        "sampling.default_hz": s.sampling.default_hz,
        "sampling.race.hz": s.sampling.race_hz,
        "sampling.system.hz": s.sampling.system_hz,
        "sampling.bio.hz": s.sampling.bio_hz,
        "battle.hunting.enter_gap": s.battle.hunting.enter_gap,
        "battle.hunting.exit_gap": s.battle.hunting.exit_gap,
        "battle.hunting.min_closing_rate": s.battle.hunting.min_closing_rate,
        "battle.hunting.activation_delay": s.battle.hunting.activation_delay,
        "battle.hunting.exit_delay": s.battle.hunting.exit_delay,
        "battle.hunting.approach_enter_gap": s.battle.hunting.approach_enter_gap,
        "battle.hunting.approach_exit_gap": s.battle.hunting.approach_exit_gap,
        "battle.hunting.attack_enter_gap": s.battle.hunting.attack_enter_gap,
        "battle.hunting.attack_exit_gap": s.battle.hunting.attack_exit_gap,
        "battle.hunting.side_by_side_enter_gap": s.battle.hunting.side_by_side_enter_gap,
        "battle.hunting.side_by_side_exit_gap": s.battle.hunting.side_by_side_exit_gap,
        "battle.hunting.intensity_min_closing_rate": s.battle.hunting.intensity_min_closing_rate,
        "battle.hunting.min_intensity_hold_s": s.battle.hunting.min_intensity_hold_s,
        "battle.hunting.update_min_interval_s": s.battle.hunting.update_min_interval_s,
        "battle.hunting.update_gap_epsilon_s": s.battle.hunting.update_gap_epsilon_s,
        "battle.overtake.max_gap": s.battle.overtake.max_gap,
        "battle.overtake.min_closing_rate": s.battle.overtake.min_closing_rate,
        "battle.hunted.enter_gap": s.battle.hunted.enter_gap,
        "battle.hunted.exit_gap": s.battle.hunted.exit_gap,
        "battle.hunted.min_closing_rate": s.battle.hunted.min_closing_rate,
        "battle.hunted.activation_delay": s.battle.hunted.activation_delay,
        "battle.hunted.exit_delay": s.battle.hunted.exit_delay,
        "battle.position_stable_seconds": s.battle.position_stable_seconds,
        "battle.gap_history_seconds": s.battle.gap_history_seconds,
        "heart_rate.enabled": s.heart_rate.enabled,
        "heart_rate.source": s.heart_rate.source,
        "heart_rate.bluetooth.device": s.heart_rate.device,
        "heart_rate.bluetooth.reconnect": s.heart_rate.reconnect,
        "heart_rate.baseline_window": s.heart_rate.baseline_window,
        "heart_rate.calm_delta": s.heart_rate.calm_delta,
        "heart_rate.focused_delta": s.heart_rate.focused_delta,
        "heart_rate.pushing_delta": s.heart_rate.pushing_delta,
        "system_info.enabled": s.system_info.enabled,
        "system_info.cpu.enabled": s.system_info.cpu_enabled,
        "system_info.gpu.enabled": s.system_info.gpu_enabled,
        "system_info.memory.enabled": s.system_info.memory_enabled,
        "system_info.lhm_dll_path": s.system_info.lhm_dll_path,
        "system_info.cpu_temp_warn": s.system_info.cpu_temp_warn,
        "system_info.cpu_temp_crit": s.system_info.cpu_temp_crit,
        "system_info.gpu_temp_warn": s.system_info.gpu_temp_warn,
        "system_info.gpu_temp_crit": s.system_info.gpu_temp_crit,
        "events.system_events_on_overlay": s.events.system_events_on_overlay,
        "events.incident_min_delta": s.events.incident_min_delta,
        "events.lap_duration": s.events.lap_duration,
        "events.lap_cooldown": s.events.lap_cooldown,
        "events.priorities.hunting": s.events.priorities.hunting,
        "events.priorities.hunted": s.events.priorities.hunted,
        "events.priorities.lap_complete": s.events.priorities.lap_complete,
        "events.priorities.personal_best": s.events.priorities.personal_best,
        "events.priorities.position_change": s.events.priorities.position_change,
        "events.priorities.incident": s.events.priorities.incident,
        "events.priorities.final_lap": s.events.priorities.final_lap,
        "events.priorities.finish": s.events.priorities.finish,
    }


def coerce_value(spec: FieldSpec, raw: Any) -> Any:
    if raw is None or raw == "":
        if spec.optional:
            return None
        return spec.default
    if spec.field_type == "bool":
        if isinstance(raw, bool):
            return raw
        return str(raw).strip().lower() in {"1", "true", "yes", "on"}
    if spec.field_type == "int":
        ivalue = int(raw)
        if spec.minimum is not None and ivalue < spec.minimum:
            raise ValueError(f"{spec.key} must be >= {spec.minimum}")
        if spec.maximum is not None and ivalue > spec.maximum:
            raise ValueError(f"{spec.key} must be <= {spec.maximum}")
        return ivalue
    if spec.field_type == "float":
        fvalue = float(raw)
        if spec.minimum is not None and fvalue < spec.minimum:
            raise ValueError(f"{spec.key} must be >= {spec.minimum}")
        if spec.maximum is not None and fvalue > spec.maximum:
            raise ValueError(f"{spec.key} must be <= {spec.maximum}")
        return fvalue
    text = str(raw).strip()
    if spec.choices and text not in spec.choices:
        raise ValueError(f"{spec.key} must be one of {spec.choices}")
    if spec.key.endswith("lhm_dll_path") or spec.key.endswith("theme"):
        if ".." in text.replace("\\", "/").split("/"):
            raise ValueError(f"{spec.key} must not contain path traversal")
    return text
