"""Shared immutable primitives for the versioned v2 narrative contracts.

This package is deliberately dependency-neutral. Timeline, facts, events,
commentary, replay and tape code may depend on it; it must not depend on those
owning domains.
"""

from .command import COMMAND_KINDS, NarrativeCommand
from .context import ApplyContextBatch, ContextBatchPart, ContextRevision, ExternalOrder
from .fact import AtomicFact, FactScope, FactStatus, FactView, load_fact_registry, semantic_key
from .narrative import (
    FunnelIdentity,
    NarrativeEvent,
    NarrativeSourceEnvelope,
    NarrativeSourceOrder,
    derived_delivery_class,
)
from .primitives import (
    MAX_SIGNED_INT64,
    BroadcastContext,
    BroadcastEpoch,
    Confidence,
    ContractViolation,
    CorrelationId,
    CycleAttemptOrdinal,
    FactQuality,
    Identifier,
    LineageId,
    MonotonicMs,
    OccurrenceId,
    PlanningSeedMaterial,
    ProcessInstanceId,
    ProcessMonotonicTime,
    ScalarType,
    SchemaVersion,
    SessionClock,
    Sha256Hash,
    SourceSequence,
    Stage,
    StreamClock,
    StreamEpoch,
    ValidityWindow,
    VehiclePhase,
    canonical_json,
    canonical_sha256,
    deterministic_planning_seed,
    validate_occurrence_lineage,
    validate_scalar,
)
from .resources import packaged_schema_bytes
from .session import (
    SessionOccurrence,
    SessionPlan,
    SessionPlanEntry,
    SessionRef,
    UnsupportedSessionEntry,
)

__all__ = [
    "MAX_SIGNED_INT64",
    "BroadcastContext",
    "BroadcastEpoch",
    "COMMAND_KINDS",
    "ApplyContextBatch",
    "AtomicFact",
    "Confidence",
    "ContractViolation",
    "ContextBatchPart",
    "ContextRevision",
    "CorrelationId",
    "CycleAttemptOrdinal",
    "FactQuality",
    "FactScope",
    "FactStatus",
    "FactView",
    "ExternalOrder",
    "FunnelIdentity",
    "Identifier",
    "LineageId",
    "MonotonicMs",
    "NarrativeCommand",
    "NarrativeEvent",
    "NarrativeSourceEnvelope",
    "NarrativeSourceOrder",
    "OccurrenceId",
    "SessionOccurrence",
    "PlanningSeedMaterial",
    "ProcessInstanceId",
    "ProcessMonotonicTime",
    "ScalarType",
    "SchemaVersion",
    "SessionPlan",
    "SessionPlanEntry",
    "SessionRef",
    "Sha256Hash",
    "SessionClock",
    "SourceSequence",
    "Stage",
    "StreamEpoch",
    "StreamClock",
    "ValidityWindow",
    "VehiclePhase",
    "UnsupportedSessionEntry",
    "canonical_json",
    "canonical_sha256",
    "deterministic_planning_seed",
    "derived_delivery_class",
    "load_fact_registry",
    "packaged_schema_bytes",
    "semantic_key",
    "validate_occurrence_lineage",
    "validate_scalar",
]
