"""Shared immutable primitives for the versioned v2 narrative contracts.

This package is deliberately dependency-neutral. Timeline, facts, events,
commentary, replay and tape code may depend on it; it must not depend on those
owning domains.
"""

from .primitives import (
    MAX_SIGNED_INT64,
    BroadcastContext,
    BroadcastEpoch,
    Confidence,
    ContractViolation,
    CorrelationId,
    CycleAttemptOrdinal,
    FactQuality,
    Identifier,
    LineageId,
    MonotonicMs,
    OccurrenceId,
    PlanningSeedMaterial,
    ProcessInstanceId,
    ProcessMonotonicTime,
    ScalarType,
    SchemaVersion,
    SessionClock,
    Sha256Hash,
    SourceSequence,
    Stage,
    StreamClock,
    StreamEpoch,
    ValidityWindow,
    VehiclePhase,
    canonical_json,
    canonical_sha256,
    deterministic_planning_seed,
    validate_occurrence_lineage,
    validate_scalar,
)
from .resources import packaged_schema_bytes
from .session import SessionPlan, SessionPlanEntry, SessionRef, UnsupportedSessionEntry

__all__ = [
    "MAX_SIGNED_INT64",
    "BroadcastContext",
    "BroadcastEpoch",
    "Confidence",
    "ContractViolation",
    "CorrelationId",
    "CycleAttemptOrdinal",
    "FactQuality",
    "Identifier",
    "LineageId",
    "MonotonicMs",
    "OccurrenceId",
    "PlanningSeedMaterial",
    "ProcessInstanceId",
    "ProcessMonotonicTime",
    "ScalarType",
    "SchemaVersion",
    "SessionPlan",
    "SessionPlanEntry",
    "SessionRef",
    "Sha256Hash",
    "SessionClock",
    "SourceSequence",
    "Stage",
    "StreamEpoch",
    "StreamClock",
    "ValidityWindow",
    "VehiclePhase",
    "UnsupportedSessionEntry",
    "canonical_json",
    "canonical_sha256",
    "deterministic_planning_seed",
    "packaged_schema_bytes",
    "validate_occurrence_lineage",
    "validate_scalar",
]
